### ISSUE TITLE
API暴露了，建议做个PHP或者写个Python中转吧

### ISSUE THREAD

**Issue by manesec** [raywongstudy/uminfo#1]
On https://github.com/raywongstudy/uminfo/blob/aa39725a37c774cbcdfca7928c93ca4e8e11b2de/js/umBusPage.js#L148

On https://github.com/raywongstudy/uminfo/blob/aa39725a37c774cbcdfca7928c93ca4e8e11b2de/js/umCanteenPage.js#L53

用的澳大开放API，通常这个公开的话会可能会有意想不到的后果。。 

建议做个PHP或者写个Python中转吧。。

另外，uminfo.tech 网站很不错哦！

**Comment by raywongstudy** [comment]
感謝你的建議，主要因為我懶惰而且不想做Server的安全，
但是由於澳大API 平台中可以隨時更改Authorization的code,
而且可以查到那些網站的調用API,如果有人盜用我再進行處理吧：P
而且由於數據是開放所有學生都能拿取, 所以感覺沒必要盜用XD
BTW 感謝你的建議，我之後有時間再做中轉/架後台。
