### ISSUE TITLE
建议：修改 meta 可以让手机端的浏览器禁止双指放大

### ISSUE THREAD

**Issue by manesec** [raywongstudy/uminfo#2]
https://github.com/raywongstudy/uminfo/blob/aa39725a37c774cbcdfca7928c93ca4e8e11b2de/umSecrets.html#L5
https://github.com/raywongstudy/uminfo/blob/aa39725a37c774cbcdfca7928c93ca4e8e11b2de/cubeGame.html#L5
等等 。。。

建议改成：
`<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />`

能够禁止大部分主流浏览器的放大问题，但还是会有些浏览器会强制开启缩放，这样只能够用js去禁止。。。。。

**Comment by raywongstudy** [comment]
感謝你的建議，因為本來我是想更新了desktop的版本才做處理的，我下次更新時再進行更改吧：P
